version: 0.2
phases:
  install:
      runtime-versions:
          java: openjdk8
  pre_build:
    commands:
    - echo "Entered the pre_build phase"
  build:
    commands:
    - echo "Entered the build phase"
    - mvn clean prepare-package war:explode
  post_build:
    commands:
    - echo "Entered the post_build phase"
    - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*